spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/franquicia?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      enabled: true
    add-properties: true
    
server:
  port: 7070

logging:
  level:
    web: debug
    org:
      hibernate:
        SQL: debug
        
environments:
        cron:
           expression: "*/5 * * * * *"
        loggin:
              user: "nahue_marcos"
              pass: "Nahue_Marcos"